language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "nightly" # currently points to 3.6-dev


# command to install dependencies
install: "pip install -r requirements.txt"




before_install:
  - sudo apt-get update -yq
  - sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"
  - sudo apt-get install msttcorefonts -qq

  # http://conda.pydata.org/docs/travis.html#the-travis-yml-file
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

# command to run tests
script:
  - nosetests
  #- python setup.py build_ext -i
  #- python -m compileall -f .
  - python setup.py test
